### ISSUE TITLE
Showing [tunnel not connected] even though tunnel is created successfully on startup.

### ISSUE THREAD

**Issue by Kusnierz-Maciej** [fieldOfView/OctoPrint-ngrok#23] opened 2020-11-07 18:36 UTC
Hi.

My Toolbar shows Circle with cross and message [tunnel not connected] even though in ngrok panel I see that tunnel got created just after powering raspberry pi. And I can connect via it too.

Here are parts of log with ngrok errors.
[ngrok_log_parts.txt](https://github.com/fieldOfView/OctoPrint-ngrok/files/5505274/ngrok_log_parts.txt)

**Comment by fieldOfView** [comment] 2020-11-08 17:06
It looks like this may be caused by a breaking change in the python bindings for ngrok. I'll look into a fix tomorrow.

**Comment by Kusnierz-Maciej** [comment] 2020-11-08 20:35
@fieldOfView - Thank you very much. Looking forward for update.

**Comment by fieldOfView** [comment] 2020-11-09 13:54
Should be fixed with 708f287

I'll keep this issue open until I publish a fixed version.

**Closed as completed** 2020-11-09 15:40 UTC
Labels: bug, fixed, 3rd party
