### ISSUE TITLE
Using a paid Ngrok account with Reserved subdomain with the plugin

### ISSUE THREAD

**Issue by inomad360** [fieldOfView/OctoPrint-ngrok#10] opened 2020-07-09 11:32 UTC
Amazing plug-in and thank you. I wanted a fixed ngrok subdomain to access my octopi and therefore got a paid basic ngrok account. I have my sub domain defined in the ngrok dashboard. It is also entered into the plug-in settings as a sub domain. However the plug-in continues to assign a random subdomain as if I do not have a paid account. 

How do I have the plug-in connect with my sub domain that is defined in the settings? Thank you

![screenshot-31](https://user-images.githubusercontent.com/68062006/87034638-2825dc80-c1b6-11ea-9789-16dbe4d2705e.jpg)

**Comment by fieldOfView** [comment] 2020-07-09 11:36
I'm marking this as a duplicate of https://github.com/fieldOfView/OctoPrint-ngrok/issues/6. I will shortly update that issue with a development snapshot for you to test/use. Sorry for the inconvenience.

**Closed as completed by fieldOfView** 2020-07-09 11:36 UTC
Labels: duplicate

**Comment by fieldOfView** [comment] 2020-07-09 11:46
Please see this comment: https://github.com/fieldOfView/OctoPrint-ngrok/issues/6#issuecomment-656079814
